server:
  port: 8084  

spring:
  application:
    name: movienight-payment
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movie_night
    username: postgres
    password: root
