server:
  port: 8081

spring:
  application:
    name: movienight-auth
  mail:
    host: smtp.gmail.com
    port: 587
    username: movienightukraine@gmail.com
    password: MNstartup2020
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movie_night
    username: postgres
    password: root
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

user:
  oauth:
    clientId: R2dpxQ3vPrtfgF72
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    redirectUris: https://www.postman.com/oauth2/callback
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: refresh
