server:
  port: 8084  

spring:
  application:
    name: movienight-payment
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movienight-payment
      auto-index-creation: false
