server:
  port: 8082 

spring:
  application:
    name: movienight-payment
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movie_night_payment
    username: postgres
    password: root
